interface Env { BOT_TOKEN:string; WEBHOOK_SECRET:string; CHANNEL_USERNAME?:string; }
async function tg(env:Env, method:string, payload:Record<string,unknown>={}):Promise<any>{const r=await fetch(`https://api.telegram.org/bot${env.BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json<any>();if(!d.ok)throw new Error(d.description||"Telegram API error");return d.result;}
async function send(env:Env,id:string|number,text:string){return tg(env,"sendMessage",{chat_id:id,text,parse_mode:"HTML"});}
export default {async fetch(req:Request,env:Env):Promise<Response>{const u=new URL(req.url);
if(req.method==="GET"&&u.pathname==="/")return new Response("DON'T TRY Bot is running 🖤");
if(req.method==="GET"&&u.pathname==="/health")return Response.json({ok:true,service:"dont-try-bot"});
if(req.method==="GET"&&u.pathname==="/setup"){const webhook=`${u.origin}/webhook`;const result=await tg(env,"setWebhook",{url:webhook,secret_token:env.WEBHOOK_SECRET,allowed_updates:["message"],drop_pending_updates:true});return Response.json({ok:true,webhook,result});}
if(req.method==="GET"&&u.pathname==="/webhook-info"){return Response.json({ok:true,result:await tg(env,"getWebhookInfo")});}
if(req.method==="POST"&&u.pathname==="/webhook"){if(req.headers.get("X-Telegram-Bot-Api-Secret-Token")!==env.WEBHOOK_SECRET)return new Response("Unauthorized",{status:401});const update=await req.json<any>();const m=update.message;if(!m?.text||!m.chat?.id)return Response.json({ok:true});const id=m.chat.id,text=String(m.text).trim(),channel=env.CHANNEL_USERNAME||"@i_dont_try";try{if(text==="/start")await send(env,id,"🖤 <b>DON'T TRY</b>\n\nبه اتاق کنترل DON’T TRY خوش اومدی.\n\n/test — تست اتصال ربات\n/publish — انتشار پست آزمایشی");else if(text==="/test")await send(env,id,"✅ ربات فعاله.\n\nDON'T TRY آماده‌ست.");else if(text==="/publish"){await send(env,channel,"🧠 <b>DON'T TRY — 001</b>\n\nگاهی دلت برای یک آدم تنگ نشده؛\nبرای احساسی تنگ شده که وقتی کنارش بودی داشتی.\n\n<i>بعضی حقیقت‌ها راحت نیستند.</i>\n\n#DONTTry #Psychology");await send(env,id,"🔥 پست آزمایشی با موفقیت در کانال منتشر شد.");}else await send(env,id,"دستور شناخته نشد.\n\n/start را بزن.");return Response.json({ok:true});}catch(e){console.error(e);return Response.json({ok:false},{status:500});}}
return new Response("Not found",{status:404});}};